service: twilio-flex

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    ACCOUNT_SID: ${env:ACCOUNT_SID}
    AUTH_TOKEN: ${env:AUTH_TOKEN}
    API_KEY: ${env:API_KEY}
    API_SECRET: ${env:API_SECRET}
    ADDRESS_SID: ${env:ADDRESS_SID}
    CONVERSATIONS_SERVICE_SID: ${env:CONVERSATIONS_SERVICE_SID}
    ALLOWED_ORIGINS: https://localhost:48264,https://merchandiser-web.survey-stage.com,https://merchandiser-web.survey.com
    DOWNLOAD_TRANSCRIPT_ENABLED: false
    EMAIL_TRANSCRIPT_ENABLED: false

functions:
  handler:
    handler: index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          
resources:
  Resources:
    ApiGatewayCustomDomain:
      Type: AWS::ApiGateway::DomainName
      Properties:
        DomainName: twilio-flex.${env:AWS_HOSTED_ZONE_DOMAIN}
        EndpointConfiguration: REGIONAL
        RegionalCertificateArn: ${env:AWS_CERTIFICATE_ARN}

    ApiGatewayBasePathMapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        DomainName: !Ref ApiGatewayCustomDomain
        RestApiId: !Ref ApiGatewayRestApi
        Stage: !Ref ApiGatewayStage
        BasePath: ''

    Route53RecordSet:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ${env:AWS_HOSTED_ZONE_ID}
        Name: twilio-flex.${env:AWS_HOSTED_ZONE_DOMAIN}
        Type: A
        AliasTarget:
          DNSName: !GetAtt ApiGatewayCustomDomain.RegionalDomainName
          HostedZoneId: !GetAtt ApiGatewayCustomDomain.RegionalHostedZoneId